### ISSUE TITLE
移除 --runner 对 url 的支持

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro-server#10]
两个关联问题：
1. #7 接入测试覆盖率
2. totorojs/totoro#64 客户端 http 服务外网无法访问

**Comment by fool2fish** [comment]
使用 totoro 的项目必须遵循如下文件结构：

```
projectname/
    src/ or lib/
    tests/ or test/
        runner.html or index.html
        totoro-adapter.js
    totoro-config.json
```
- 源码必须放在 src 文件夹中
- 测试文件夹可叫 tests 或 test
- runner 可名为 runner.html 或 index.html

仅允许在 projectname 目录运行 totoro

**Comment by fool2fish** [comment]
继续支持 url 的方式，使用起来比较方便，至于覆盖率，在服务端实现，没有影响，约束是：url 必须是外网可访问的

**Comment by lifesinger** [comment]
赞同，保持简单。

2013/7/8 fool2fish notifications@github.com

> 继续支持 url 的方式，使用起来比较方便，至于覆盖率，在服务端实现，没有影响，约束是：url 必须是外网可访问的
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro-server/issues/10#issuecomment-20583559
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香
