### ISSUE TITLE
考察阿里云服务

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro-server#15]
1. 提升服务稳定性
2. 未来计划对外开放

参考阿里云内网购买计划：http://www.aliway.com/read.php?fid=38&page=1&tid=200922

**Comment by lifesinger** [comment]
好好考察下
如果需要费用，交给我去申请就好

2013/6/4 fool2fish notifications@github.com

> 1. 提升服务稳定性
> 2. 未来计划对外开放
> 
> 参考阿里云内网购买计划：http://www.aliway.com/read.php?fid=38&page=1&tid=200922
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro-server/issues/15
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by leoner** [comment]
@lifesinger @fool2fish  联系了下，结果人家这个资源没有包括支付宝，让我们去咨询 PE，我们的 PE 是谁呀

**Comment by leoner** [comment]
相关内容已经放到 https://github.com/alipay/wd-tech-team/issues/584

**Comment by leoner** [comment]
明年在具体考虑.

**Comment by fool2fish** [comment]
不一定是明年啦，我们技术上的问题解决了之后其实就可以考虑的，反正是先放着
