### ISSUE TITLE
客户端和服务端的版本协调问题

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro-server#18]
目前每个版本的服务端只记录了最低支持的客户端版本，没有记录最高支持的客户端版本，随着客户端版本不断升高，如果使用的是比较老的服务，就有可能通过版本检测但实际使用不了的情况(目前还是小概率事件)

抛个砖，说个解决方案：

前两位版本一致的客户端和服务端可兼容，不一致的就不兼容，升级的时候也要考虑到这个情况。

如果任何只需要一方做的修改，就只升第三位版本号，这个约定基于这样的假设：任何大的修改都需要客户端和服务端配置修改。

如果需要同时升客户端和服务端，那么此次发布就必须升第一位或第二位版本号。

**Comment by leoner** [comment]
第三位一般是 bugfix.  一般的不兼容主要是通过第一位版本号的变更。
不过目前看来我们的整体结构基本上不会有太大的变化了，这样也应该能接受。

**Comment by fool2fish** [comment]
或者每个发布的 server 版本都会预定义一个兼容的 client 版本范围，client 版本更新到范围上线，不管下一个版本是不是兼容，都需要升级 server 版本？

更新主版本的是针对项目自身的，不过咱们是两个模块版本协调，不太一样啊
