### ISSUE TITLE
在server端添加adapter的处理

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro-server#2]
1. 首先如果像 seajs 这种，在客户端指定了 adapter 和 runner 那么我们就在客户端对 adapter 合并到 runenr 中.
2. 如果对于我们的基础框架，由于我们可以很容易探测到 adapter ，那么我么也是在客户端合并.
3. 如果用户指定的是 外部的 url， 也就是和客户端的地址不匹配的时候，我们在服务器端在进行 adapter 的处理.

目前在 server 端就是处理第三种情况

**Comment by fool2fish** [comment]
adapter总是在server端处理
