### ISSUE TITLE
替换 useragent 为 detector

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro-server#21]
detector 为我们自己的同学开发，而且浏览器的信息分析的很全面。看看后续是否需要替换过来, 先记录下.
https://github.com/hotoo/node-detector/

**Comment by leoner** [comment]
暂时先不考虑.

**Comment by fool2fish** [comment]
配合公司升级ie11，替换为 detector，可以更快的对新型浏览器做出反应。其中需要注意的点：
- chrome 为四位版本号，在进行版本比较的时候需要注意
- detect 直接返回一个 json ，无 toString()

先换成detect，再处理两个相关问题：
- #24 改进 totoro list 的显示
- #23 升级未指定 --browsers 时的浏览器分配策略

**Comment by hotoo** [comment]
版本号比较可以考虑使用 https://github.com/hotoo/versioning
