### ISSUE TITLE
升级未指定 --browsers 时的浏览器分配策略

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro-server#23]
原因：
1. ua 使用 detector 进行 parse，数据格式发生变更
2. ie11 发布，之前对 ie 只获取大 版本的情况可能不适用，比如 ie11 的平板版本和 pc 版本可能有较大差异，需要考虑平台因素

现在机器比较少，如果赶时间的话，可以不考虑分组之类的问题，只要有一点不一样，就作为一个单独的需要跑的浏览器，比如平板上的 ie11 和 pc 上的 ie11

**Comment by leoner** [comment]
```
totoro --browsers=desktop
totoro --browsers=mobile, ie6.0
```

客户端支持上面两种方式的调用, 服务端会根据用户指定的 pc 类型找到对应的浏览器.
