### ISSUE TITLE
改进 totoro list 的显示

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro-server#24]
- 显示是否需要分组，根据设备、os、浏览器名等因素
- 是否合并小版本显示，还是显示完整的版本号

**Comment by leoner** [comment]
关于分类, 有3个维度:
- 按设备, 比如 pc, mac 系列 具体可参考 [设备分类](https://github.com/aralejs/detector#number-detectordevicedevice_name)
- 比如按照操作系统, ios, windows [操作系统分类](https://github.com/aralejs/detector#number-detectorosos_name)
- 无线设备和 pc 设备. 不过这个就需要我们想好如何对设备进行划分.

**Comment by leoner** [comment]
按照 pc 和 phone 进行分类显示:

```
PC:
    Chrome 26.0.1410 / Windows 7 [1]
    Firefox 22.0.0 / Windows XP [1]
    IE 10.0.0 / Windows 7 [1]
    IE 6.0.0 / Windows XP [1]
    IE 8.0.0 / Windows 7 [1]
    Safari 5.1.7 / Windows 7 [1]
Phone: 
    Chrome 26.0.1410 / ios 6.0 [1]
    Firefox 22.0.0 / android 4.0 [1]
Other:
    无法识别的分类
```

**Comment by leoner** [comment]
还有一个问题就是具体某类设备中是否在具体对 浏览器和 操作系统在进行分类.

个人感觉应该按照浏览器类型可以在进行分类? 比如 ie 系列可以放到一起展示.

还有一个浏览器版本比较的问题, 目前我倾向完全按照解析出来的版本号比较.

**Comment by fool2fish** [comment]
如果某个分类下没有就不显示类别吧？

**Comment by leoner** [comment]
确定分为 Desktop, Mobile, Other 三组.其中通过 parse ua 的设备名称来换分, 如果匹配到 [pc, mac, linux]  则是 Desktop, 其他已匹配的是 Mobile. 无法匹配的是 Other.
