### ISSUE TITLE
关于 Labor 对象结构的调整

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro-server#26]
对于挂载多个相同的浏览器我们目前要对应多个 Labor 实例对象， 但是他们之间除了 labor id 不同， 其实其他的都一样。 而且目前我们计算某个 labor 的数量时(list) 也只能遍历产生。 那么我们能不能对于相同的Labor 我们只保存一个实例， 有相同对象的 Labor 过来时， 我们只需要更新数量和 laborId 这两个参数就行了？
@fool2fish

**Comment by fool2fish** [comment]
不是很赞成这样做，一来有悖labor给人的直观印象，和order什么的概念上也不对等了，二来事情会变复杂，他们除了laborid不同之外，还保存有socket实例，有非常多自己独立的行为，不仅内部处理会变复杂，外部也一样，比如 manger.add(labor) 和 order.add(labor)，况且在可见的很长时间内，不会出现很多同浏览器同时挂载的情况

**Comment by leoner** [comment]
好, 那先不考虑了.
