### ISSUE TITLE
改进 manager.js 的 distribute() 和 autoBrowsers()

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro-server#29]
如题

**Comment by fool2fish** [comment]
## 比较扁平化的 labors: {laborId: labor} 和设备分组的 groupedLabors: {group: {laborId: labor}} 对 list()，autoBrowsers() 和 distribute() 复杂度的影响

### 前置条件
- 一共有 m 个 labors
- labors 分为 desktop 和 mobile 两组，其中属于 desktop 的 labors 有 n 个，属于 mobile 的 labors 有 m-n 个

### 比较结果

#### list()

不分组：

```
var rt = {}
Object.keys(labors).forEach(function(labor){
  var ua = labor.ua
  var group = ua.group
  rt.group = rt.group || {}
  rt.group[labor.id] = ua.toString()
})
```

分组：

```
var rt = {}
Object.keys(groupedLabors).forEach(function(group, groupName){
  rt[groupName] = {}
  Object.keys(group).forEach(function(labor){
    rt[groupName][labor.id] = labor.ua.toString()
  })
})
```

显然，上述两种情况下，单次运行 list() 都必须对所有的 labors 进行遍历，计算次数为 m 次

### autoBrowsers()

不分组：

```
Object.keys(labors).forEach(function(labor){
  var ua = labor.ua
  if (ua.group === 'desktop') {
    ...
  }
})
```

分组：

```
Object.keys(groupedLabors.desktop).forEach(function(labor){
  ...
})
```

单次运行 autoBrowsers()，在不分组的情况下需要遍历 m 次，分组的情况下需要遍历 n 次，只要不是 n << m-n 的情况（实际上应该是 n >> m-n），两者效率差异不大

同样的，对于 --browsers=desktop 的情况，不分组需要遍历 m 次，分组需要遍历 n 次

#### distribute()

考虑每匹配一个 browser 的消耗，这需要分两种情况来考虑（使用摊还分析来算）：
1. 用户习惯于指定 os  
   - 不分组的平均遍历次数为  m/2
   - 分组的平均遍历次数为 n/2
2. 用户习惯于不指定os 
   - 不分组 的平均遍历次数为 m/2
   - 分组 的平均遍历次数为 m/2

所以每次计算 distribute()，平均遍历 browsers.length *  匹配单个 browser 的消耗 

可见，只有用户总是指定 os 的时候，且总是指定包含 labor 数量极少的分组才会有少许优势

### 其他

由于 autoBrowsers 是最主流的 --browser 指定方式，而 autoBrowsers 的返回值不包括 os，所以 distribute 的时候分组没有任何优势

另外，由于 autoBrowsers 的返回值不包括 os，所以 distribute 的时候也未必就是匹配 desktop 类型的设备，所以从目前的情况来看，应该取消 autoBrowsers 从特定的 desktop 分组中进行选取

### ！！哪些地方可以提高 distribute() 的效率
1. 显然需要一个高效的 isMatch(browser, labor)
   - 目前已作的优化是把 formatBrowser() 移至 Order 中执行，成为 order 初始化时的一次性消耗，而不用每次执行的时候 format 一遍
   - 其他暂时没有更好的想法了
2. 另外，需要注意的是减少重复匹配的消耗（也就是说当一开始没有合适的 labor 匹配的时候）。这种情况下不应该对所有的 labor 进行遍历（因为有些 labor 第一次匹配就不符合要求，后面也不会符合要求，因为状态忙而匹配失败的 labor 除外），所以应该只对变动的 labor 进行遍历，即减少上述描述中的 m 值

**Comment by fool2fish** [comment]
目前只剩高效的 isMatch() 未进行改进，暂时到这，等以后很的有性能问题再解决

**Comment by leoner** [comment]
```
totoro --browsers=mobile
```

这种方式不支持了？ 也就是说用户必须自己明确浏览器是啥了？

**Comment by leoner** [comment]
目前分组不分组确实不是主要问题， 因为毕竟 labor 不会太多。 不管全部循环， 还是循环一部分差别不是很大。

主要还是在 distribute 存在潜在冗余遍历， 从而造成潜在的性能问题. 因为每当有 order新增，labor 添加和释放， 都会执行。其中一个情况就是:
**如果有10个 order 等待 IE/6.0, IE/7.0. 每当我们Labor 发生变化的时候， 都需要重新遍历这 10个 order. 而且每次都要遍历这个 order 的 waitingBrowsers. 其实应该只有新增了 Order 需要的浏览器的时候，才需要通知 Order. 而现在是反复的询问**

我的想法还是如果能做到每次新增 Order 以后, 只需要对 labor 查找一次, 那么当有合适的 labor 的时候, 才会通知相应的 Order 去执行.

**Comment by lifesinger** [comment]
可预见的浏览器不会太多，最多 100 个？

因此这个 issue 讨论的效率问题，感觉并不存在呀。无论怎么折腾，应该都不会有什么效率问题。

order 倒有可能很多，但目前应该也不是问题。

**Comment by fool2fish** [comment]
@leoner 
1. 不支持分组，出于两个考虑，一是用户还没有需求这用，而且我们也没有 mobile 的 labor，二是之前的代码逻辑不完备，即使根据分组指定了 browsers，真正匹配的时候还是有可能匹配到别的分组的 labor，因为我们没有限定 os
2. browser 和 labor 冗余匹配问题，在第二个提交中已经基本解决了。所有的浏览器跟 order 理论上只有一次判断消耗。

**Comment by leoner** [comment]
首先如果按照现有用户数量的情况下, 不管怎么样应该都不会有效率问题呀.

 但是在后续用户多的时候还是可能有我提到的那个情况呀. 假如有10个Order( **waitingOrders** ) 在等待 ie/6,ie/7( **waitingBrowsers** ) . 那么每当我们有 labor 发生变化时, 我们都会执行 **distribute** , 然后重新去遍历 **waitingsOrder**. 然后继续遍历 **waitingBrowsrs**, 假如我们现在有20个 Labor( **availableLabors** ). 那么我们还要重复遍历20次 labor.

也就是说如果现在有 10个Order, 2个 WaigingsOrder, 20 个 Labor.  那么每次labor 有变化(如果变化的 labor 不是 order 需要的), 其实就要执行 400次 isMatch 方法呀.

```
distribute: function(){
       ......
        Object.keys(waitingOrders).forEach(function(orderId) {
            var order = waitingOrders[orderId]
            var waitingBrowsers = order.waitingBrowsers
            var parsedBrowsers = order.parsedBrowsers

            Object.keys(waitingBrowsers).forEach(function(browser) {
                var parsedBrowser = parsedBrowsers[browser]
                for (var i in availableLabors) {
                    var labor = availableLabors[i]
                    if (isMatch(parsedBrowser, labor.ua)) {
                        order.add(labor, browser)
                        labor.add(order)
                        break
                    }
                }
            })
        })
    },
```

**Comment by leoner** [comment]
调用方法那里已经做了控制, 效率应该好了很多. 那目前应该没有啥问题了呀.
