### ISSUE TITLE
测试中的 alert 的处理

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro-server#30]
发现如果测试用例中有 alert 会阻塞 safari 浏览器. 其他浏览器没有影响.

**Comment by leoner** [comment]
好像 ie9, ie11 都挂掉了!

**Comment by fool2fish** [comment]
我怎么记得这个问题所有的测试框架都有处理？确证下？

**Comment by leoner** [comment]
恩, 就是我 list 的时候发现缺少 safari. 然后查看时, 发现 safari 有一个 alert. 确定后, 就恢复了.

**Comment by leoner** [comment]
ie9, ie11 断掉链接不知道是不是这个原因.这都需要排查下.

**Comment by leoner** [comment]
确定了, alert 都会被弹出, 只是有些浏览器弹出后:
1. 有些浏览器还可以继续通过 socket 进行通信
2. 有些不会通信, 但是由于有监控, 如果无法通信会对浏览器进行处理, 但是好像还是会继续执行此任务.
3. safari 是在 list 的时候, 无法看到, 其他浏览器还都能看到.

**Comment by hotoo** [comment]
测试用例里面的 alert 有什么意义？是否可以直接去掉？

**Comment by leoner** [comment]
是的, 应该是要自动过滤掉的, 记得以前测试框架会进行处理, 所以我们本地么有对代码进行处理. 看现在的情况, 我们可能自己在做一次检查了.

**Comment by lifesinger** [comment]
将 spec 里的  alert 重置掉，好像有点麻烦，不能影响正常的 alert 运行。

2013/8/5 hui notifications@github.com

> 是的, 应该是要自动过滤掉的, 记得以前测试框架会进行处理, 所以我们本地么有对代码进行处理. 看现在的情况, 我们可能自己在做一次检查了.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro-server/issues/30#issuecomment-22083612
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by leoner** [comment]
https://github.com/turn/queen/blob/stable/static/queen.js#L3817 
这个应该就是我们以前看到过的处理的地方.  那我们也按照这个自己处理下吧. @fool2fish

**Comment by leoner** [comment]
目前考虑 alert, prompt 这些在测试中也算错误的处理, 所以添加到 onerror.js 中了.

**Comment by fool2fish** [comment]
1. onerror.js 改名为 totoro.js （作为一个综合性的文件处理好了，alert 也不能算是错误）
2. adapter.js line:45 的 window.totoro = (window.opener || window.top).totoro 放到 totoro.js 最前面，其次是覆盖 alert ，最后才是 onerror
3. 修改 adapter.js 对应的测试用例
