### ISSUE TITLE
性能消耗详细分析

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro-server#38]
主要有下面几个时间点:
- 客户端和server 建立连接. 
- labor 分配
- labor 工作
- labor 完成后到客户端结束时间.

**Comment by lifesinger** [comment]
有进一步的数据吗？

**Comment by leoner** [comment]
本周会有详细数据出来呀.

**Comment by leoner** [comment]
首先我们在 totoro 端可以监控下面三个时间:
- 客户端和server 建立连接的耗时. 我们在 lanchTest 中进行统计
  
  ```
     Client.prototype.launchTest = function() {
         console.time('connect-server')
         .....
         socket.on('connect', function () {
              console.timeEnd('connect-server')
  ```
- 客户端建立连接后, 第一次收到消息的时间, 这个时间应该就是可以认为是 labor 的分配和建立时间
  
  ```
         console.time('firstReport')
         socket.emit('init', {})
         ....
         socket.on('report', function(reports) {
  
          if (firstReport) {
              console.timeEnd('firstReport')
  ```
- 执行时间. 就是第一次收到报告到收到结束报告的时间.
  
  ```
        case 'endAll':
                  that.report(info, cfg.verbose)
                  console.timeEnd('duration')
                  that.destroy()
                  break
              default:
  ```

由于浏览器的多少可能是 labor 时间分配长短的主要因素, 所以我们会一直不断的增加浏览器, 来看这个时间的变化. 其中会有两组时间, 第一组是一个比较简单的项目, 另外一个是比较复杂的项目
- ie6 
  - connect-server: 208ms firstReport: 985ms duration: 955ms
  - connect-server: 205ms firstReport: 985ms duration: 8608ms
- ie6, ie7
  -  connect-server: 209ms firstReport: 995ms duration: 952ms
  -  connect-server: 209ms firstReport: 993ms duration: 8620ms
- ie6, ie7, ie8
  -  connect-server: 208ms firstReport:  985ms duration: 957ms
  -  connect-server: 221ms firstReport: 992ms  duration: 9559ms
- ie6, ie7, ie8, ie9
  -  connect-server: 220ms firstReport:  987ms duration: 958ms
  -  connect-server: 213ms firstReport: 996ms duration: 9564ms
- ie6, ie7, ie8, ie9, ie10,
  -  connect-server: 211ms firstReport: 993ms duration: 957ms
  -  connect-server: 210ms firstReport:  994ms duration: 10543ms
- ie6, ie7, ie8, ie9, ie10, ie11, chrome, firefox, safari
  -  connect-server: 221ms firstReport:  994ms duration: 961ms
  -  connect-server: 206ms  firstReport:  961ms duration: 11497ms

上面的测试基本上都是在服务独享的状态下的. 从这个数据我们可以看出在正常情况下 labor 的分配时间不会随浏览器的多少. 而有太大的变化.  不过这个具体的 1s 时间需要在 server 端进行拆分, 看看具体是在那里耗时最长. 

总之: 目前看来从用户开始执行到看到第一个反馈, 基本上需要 1.3s 左右的时间, 这个时间应该还可以接受, 但是有用户反馈会有更长的等待, 这个就需要看看怎么才能模拟了呀.

**Comment by fool2fish** [comment]
目前没有 client 向 server 传递 log 的机制，如何获得这些数据？

ps：我觉得客户端消耗有限，不用监控，主要应该从服务端获取相关数据啊

**Comment by leoner** [comment]
极端测试一:
- 同时测试8个比较复杂的项目. 前两个时间没有太大变化. 但是最后一个执行时间, 如下:
  `114993ms, 121730ms, 46933ms, 104327ms, 84289ms, 98513ms, 99581ms, 93939ms`
  在独享情况下, 我们看到上面的时间是 **11497ms** 但是当同时执行的时候, 时间会翻好几倍. 所以iframe 的方式, 如果在多个任务情况下, 性能还是比较差的.

**Comment by leoner** [comment]
从客户端我们首先可以得到第一响应时间. 这个时间其实应该我们能控制的. 也就是 **服务器得到通知到告诉客户端开始执行这个时间** . 而后面的执行时间的效率, 主要就是从浏览器执行和通信进行排查了.

**Comment by leoner** [comment]
上面的测试数据中的 **firstReport** 可以忽略了. 因为在 server 端有一个 950ms 的等待时间. 然后把这个等待时间改的很短后, 可以基本得到的数据是
- 服务连接时间 200ms 左右
- 数据传递时间应该在 50ms 左右

不过这个时间可以调的短些, 因为可以更早的给用户响应, 然后通信时间应该不是瓶颈呀.

**Comment by fool2fish** [comment]
我觉得只需要监控请求到服务端了之后的行为啊，从测试数据来看，客户端单独的操作基本也是稳定的，不需要监控

**Comment by fool2fish** [comment]
ps：同时执行多个 iframe 效率差，这个是显然的，不过我也不确定同样的情况用new window 执行是不是会好点，new window 还有个潜在的风险，就是如果new window打开的是新tab，那么某些高级浏览器下面极有可能失焦的tab不执行脚本，这样的话就悲剧了

**Comment by leoner** [comment]
暂时先关闭, 等到后续改用 new window 后看看性能如何.
