### ISSUE TITLE
重新考虑new window中运行测试

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro-server#41]
之前从效率的角度没有采用 new window 的运行的方案

最近遇到几个在iframe中运行测试用例引起的诡异问题，重新审视这个方案十分有必要

老的参见 totorojs/totoro#44

**Comment by lifesinger** [comment]
在iframe中运行测试用例引起的诡异问题

具体是啥诡异问题？

2013/9/2 fool2fish notifications@github.com

> 之前从效率的角度没有采用 new window 的运行的方案
> 
> 最近遇到几个在iframe中运行测试用例引起的诡异问题，重新审视这个方案十分有必要
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro-server/issues/41
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by leoner** [comment]
那我们在这里把已知问题罗列下吧:
- xbox 里面导致 ie6 大概率的崩溃. 原因可能是 iframe 里嵌套 iframe, 引用资源的问题
- 对于某些位置计算, iframe 的可视区域可能会影响某些计算值

@fool2fish  再补充些呀.

**Comment by fool2fish** [comment]
很多啦，比如：
- 书记的那个问题
- dom属性的计算，典型地：空 div 的 offsetWidth/offsetHeight 均为 0
- 然后测试iframe的尺寸也是多次变更，从最开始0x0，到60x60，到100%x120

**Comment by lifesinger** [comment]
书记的那个问题可以排除掉

2013/9/3 fool2fish notifications@github.com

> 很多啦，比如：
> - 书记的那个问题
> - dom属性的计算，典型地：空 div 的 offsetWidth/offsetHeight 均为 0
> - 然后测试iframe的尺寸也是多次变更，从最开始0x0，到60x60，到100%x120
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro-server/issues/41#issuecomment-23687343
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by fool2fish** [comment]
所有测试浏览器必须要设置允许弹出窗口

**Comment by fool2fish** [comment]
移动端 window.open 废的，仍采用 iframe 的方式
