### ISSUE TITLE
labor 的 iframe 的高度

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro-server#42]
目前高度为 120px. 这个高度导致了一些和位置相关的模块测试报错, 比如 arale.tip. 现在临时把高度改为 300px. 后续看看有没有一种手段让模块自己进行配置?

这个也和 #41 的问题类似, 如果使用 #41 的新窗口, 也没有这个问题了.

**Comment by leoner** [comment]
目前在服务器上临时改为 320px, 后续看看最终的方案!

**Comment by leoner** [comment]
是否可以在客户端配置参数, 用来指定创建的 iframe 的大小? 专门用来针对这些对窗口有特殊要求的项目?

传递的方式可以支持写在 tests 用例中? 或者 package.json 啥的.

**Comment by fool2fish** [comment]
new window 的方案应该可以解决这个问题

但暂不考虑增加这样的选项出于以下考虑：
1. 这个参数是什么意思？
2. 什么情况下应该设置这个参数？
3. 设置什么值合适？

这三个问题是用户很难理解的

**Comment by leoner** [comment]
恩是的, 而且这个参数在哪里配置也不好弄,  现在这个完全是基于我们确定使用 iframe 时的方案. 所以只是先提出来. 如果 new window 可行, 这个就可以忽略了.

**Comment by fool2fish** [comment]
嗯，我尽快把 new window 这个方案确定下，如果ok的话我们之前好多头疼的问题就可以解决了

**Comment by leoner** [comment]
恩, 呵呵, 不过我估计还是会有很多新的头疼问题的产生的呀.
