### ISSUE TITLE
提供一个简单静态页面服务, 用来验证测试用例在iframe中运行是存在问题

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro-server#44]
提供一个页面, 运行用户添加 url, 生成一个和 labor 产生类似的 iframe.

**Comment by leoner** [comment]
临时可用地址 http://10.15.52.87:9999/iframe.html. 
会在 0.5.0 中正式发布.

**Comment by fool2fish** [comment]
这些都是因为 iframe 运行测试引起的问题，既然已经在考虑 new window 重新启用的方案了，怎么能不验证 new window 不可行的情况下做这些事情呢？

**Comment by leoner** [comment]
恩, 因为 new window 的方式我们还是在前期调研, 真正运行起来的时候也可能会遇到我们在 iframe 类似的各种诡异问题. 所以最理想的情况下也是这两种方案可能要并行一段时间, 然后才能确定到底采用哪一种.
