### ISSUE TITLE
增加 labor 分配次数限制

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro-server#47]
在有些情况下, 测试用例回导致 labor 的 socket.io 中断, 然后由于 labor 有自动重连的机制, 那么这个情况就回反复的分配 labor. 现在增加了最大分配次数. 如果同一个 Order 对同一个 labor 分配超过 **3次** 我们就终止分配.

**Comment by fool2fish** [comment]
还有一个潜在问题，暂时不处理：

如果不是labor挂调，而是运行 runner 的 iframe 或者 window 自己卡死了，那么结果就是该浏览器运行的这个测试超时。小概率事件，如果以后这种情况多起来的话，需要在 labor.js 端做个超时控制。
