### ISSUE TITLE
totoro 后续开发计划讨论（已迁移至 totorojs.org）

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro-server#48]
新地址：https://github.com/totorojs/totorojs.org/issues/9

**Comment by lifesinger** [comment]
建议从 totoro 的角度去规划，比如 totoro 0.5 的预期功能，建一个 milestone，给一个预估时间，并将可分解的功能点分解到独立 issue 中。这样总体进度 github 就能统计出来，规划也更一目了然。

**Comment by fool2fish** [comment]
totoro一直都有milestone，这个issue是用来讨论的
ps：什么叫从 totoro 的角度？

**Comment by leoner** [comment]
针对某个浏览器可以指定最大并发数, 比如 IE 可以指定并发为 **1**

**Comment by lifesinger** [comment]
@leoner 可指定并发数是出于什么考虑？缘由是什么？

**Comment by leoner** [comment]
主要是 IE6,7 性能的问题, 如果目前有10个并发, chrome 肯定没有问题, 但是 IE6,7 就很难抗的住了, 所以可以对于这些浏览器我们可以控制同时执行测试的数目.

**Comment by leoner** [comment]
https://github.com/assaf/zombie 可以看看是否对我们有帮助?

**Comment by leoner** [comment]
- 稳定运行，给出有效的失败告警 

直接在邮件中显示出错误信息. 用户不需要在进入 hudson 进行查看.

**Comment by lifesinger** [comment]
zombie 这种可以考虑下
随着 工具环境 Castle 的推进，本地开发会成为我们的主流开发方式，那么纯本地调试也就非常重要
比如目前 seajs 和 kissy 在开发过程中，大部分情况下是在 phatomjs 下跑一下就搞定，浏览器都不用开
等要发布某个版本，或定期才用 totoro 跑下兼容性问题

因此，totoro 是否可以考虑增加一个支持：对 phantomjs 等环境下测试的无缝支持？zombie 没细看，好像是干类似的事情？

2013/10/11 hui notifications@github.com

> - 稳定运行，给出有效的失败告警 直接在邮件中显示出错误信息. 用户不需要在进入 hudson 进行查看.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro-server/issues/48#issuecomment-26119135
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by fool2fish** [comment]
要 phantomjs 有什么用？如果有的话也是要运行 `totoro --browsers=phantomjs`，还不如 `totoro --browsers=chrome` 啊

**Comment by leoner** [comment]
zombie 的定位不同, 他和Mocha 这些测试框架进行了结合, 可以针对针对一些不需要关心浏览器差异的页面功能和 ui 测试. 
我想到能用到他的地方就是收银台算是比较合适的. 因为收银台支付这块其实主要是逻辑上面的处理, 而浏览器差异其实在我们组件中已经处理了. 真正的业务上应该是不需要考虑浏览器的差异的. 我们可以通过写测试来验证各种支付流程. 不过牵扯到各种控件啥的, 估计运行起来也够呛, 不过以后还是可以看看的.
