### ISSUE TITLE
浏览器通过新开窗口的方式的内存占用情况

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro-server#51]
一个小时执行一遍所有的 arale 模块的测试用例, 明天查看浏览器的内存消耗情况.
### 87
- Node: 70, 49, 22M
- FF: 55M
- Chrome: 18, 6M
- IE/10.0: 4, 6, 7M
### 88
- IE/7.0: 33M
- Node: 20M
### 89
- IE/8.0: 17M
- Safari: 15M
- Node: 23M
### 90
- IE/6.0: 28M
- Node: 26M
### 145
- IE/11.0: 14.7M
- FF: 56M
- Chrome: 21.4M
### 146
- IE/11.0: 12.1M
- FF: 51.0M
  -Chrome: 14.6M
### 147
- IE/9.0: 16M
- FF: 56M
- Chrome: 18M
- Node: 23M

有些浏览器可能不会被分配到, 所以主要以 IE测试为主.

**Comment by leoner** [comment]
### 87
- Node: 49, 79,79M
- FF: 85M
- Chrome: 51, 24M
- IE/10.0: 11, 6, 56M (不过IE已经无响应, 并出现了停止工作的对话框, 确定后, IE 关闭)

### 88
- IE/7.0: 433M
- Node: 47M

### 89
- IE/8.0: 335M
- Safari: 50M
- Node: 80M

### 90
- IE/6.0: 300M (进程僵死, 是出现错误对话框, 确定后浏览器关闭)
- Node: 46M

### 145
- IE/11.0: 101M
- FF: 52M
- Chrome: 16.8M

### 146
- IE/11.0: 12.1M
- FF: 51.0M
  -Chrome: 14.6M

### 147
- IE/9.0: 281M
- FF: 56M
- Chrome: 18M
- Node: 80M

**Comment by leoner** [comment]
通过单独测试用例查看浏览器内存变化(IE7, IE8). IE6 由于每个进程内存单独控制, 所以只要关闭窗口内存恢复正常.
IE7和IE8 分别保持一个空白的 Tab. 然后打开新的 Tab 进行测试. 测试完成后, 记录内存变化情况. 
- IE7 **29-(38,36)-33M** |  **33-(40,39)-36M** | **36-(43,42)-39M**
- IE8 **19-23-22M**  | **22-27-26M**  | **26-30-29M**

第一个数据指的是初始内存. (38,36) 这种指的是执行过程中最高达到38, 但是执行完成后会回落到36. 最后一个数值是关闭页面后, 内存维持的数值.

所以从这个数据感觉我们测试用例本身可能就存在内存上面的问题?

> 执行的是 http://aralejs.org/autocomplete/tests/runner.html 这个页面.

**Comment by lifesinger** [comment]
执行空 runner 是什么情况？

另外昨天跟沉鱼聊到目前 ie6-7 的份额已降低到 9% 以下，很有希望一年之内继续降低到 5% 以内，到 14 年年底，甚至可以跟 PD 等全面达成不再支持 ie6-7 的约定（或非常简单粗暴的降级）。这样，totoro 在对 ie6-7 的支持上，可以简单粗暴些，只要不是严重问题，都可以暂且忽略，在 ie6-7 下保持适当的可用性就好。

**Comment by leoner** [comment]
刚才试了下IE7. 就是单独打开很多空 Tab, 内存从 30涨到50. 然后全部关闭只保留一个内存只能恢复到 40. 这都涨了10M.

**Comment by leoner** [comment]
还有一个现象就是我在 IE7 下面打开 http://aralejs.org/autocomplete/tests/runner.html 这个页面, 然后执行完后内存会涨5,6M 左右. 然后当前页面刷新, 内存持续增长. 然后我试了 www.taobao.com. 每次刷新基本上内存会恢复到原来最初的值, 然后再涨上去, 基本上波动不大.  然后试了下我们的 https://www.alipay.com 增长的更大.

**Comment by lifesinger** [comment]
试试 widget / base 的 runner.html

记得 Arale widget 曾经有过一次内存泄露问题，当时邵帅总结过，具体细节有点忘了。

**Comment by leoner** [comment]
刚才试了 ie6,7,8 全都有问题. 然后试了一个别人的测试用例, 页面刷新内存基本上都能恢复.

**Comment by leoner** [comment]
widget 试了 ie6,7每次涨2M 左右, ie8 1M 左右

**Comment by leoner** [comment]
base 好点. 内存增长不大, 基本上刷新的时候能恢复到原来的初始值.

**Comment by lifesinger** [comment]
那就是 widget destroy 的处理上还有问题
可以找找邵帅当时那份总结邮件，刚搜了下居然没搜索到

On Fri, Oct 11, 2013 at 10:26 AM, hui notifications@github.com wrote:

> base 稍微好点. 内存增长不大, 基本上刷新的时候能恢复到原来的初始值.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro-server/issues/51#issuecomment-26109232
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by leoner** [comment]
https://github.com/aralejs/aralejs.org/issues/306

**Comment by edokeh** [comment]
> 另外昨天跟沉鱼聊到目前 ie6-7 的份额已降低到 9% 以下，很有希望一年之内继续降低到 5% 以内，到 14 年年底，甚至可以跟 PD 等全面达成不再支持 ie6-7 的约定（或非常简单粗暴的降级）。

喜闻乐见，赶紧动手吧，小弟们紧跟其后啊

**Comment by hotoo** [comment]
Windows XP, IE8 是瓶颈。

**Comment by leoner** [comment]
后续在 https://github.com/aralejs/aralejs.org/issues/306  上跟进。
