### ISSUE TITLE
启动totoro-server错误

### ISSUE THREAD

**Issue by wiz-Cll** [totorojs/totoro-server#54]
执行命令totoro-server时报这个错误: 

```
info index.js:69 | Start server <192.168.1.16:9999>
connect mongo server error!
```

本机已经启动mongod了.

**Comment by wiz-Cll** [comment]
系统版本OSX10.9 

在运行此命令出错后仍可跑起totoro，在sample/simple目录中。使用chrome访问ip：9999后有totoro的页面出来，但是测试一直没动静，最后报超时的错误。

**Comment by fool2fish** [comment]
db 报错可忽略，这个是我们日志模块的问题。没跑成功的话，应该是因为浏览器的 popup 被阻塞的原因，详见：https://github.com/totorojs/totoro-server/wiki/Popup-Settings.zh 。抱歉这个忘记写在文档里了，已添加。

**Comment by wiz-Cll** [comment]
恩,现在跑起来了, totoro-server可以通过socket监控到labor的加入.
totoro也可以进行测试了.
还是建议把配置说明更清楚些, 一点点摸索真的很为难我这种测试小白啊...

比如说:
在服务器上开启totoro-server时,应配置server-host为服务器公网ip. 本机启动totoro命令时需注明totoro-server的server-host...

**Comment by fool2fish** [comment]
目前比较成熟的使用场景是局域网内，至于公网使用，只是目前实验中的功能（因为有个技术问题需要确认），所以启动 totoro-server 时没有特别提到配置公网 ip 这件事情，预计在明年初会做这个事情。

至于安装 totoro 后需要配置 --server-host 这个，我已经改醒目啦：）
