### ISSUE TITLE
测试页面直接引入jqurey会超时 是什么原因

### ISSUE THREAD

**Issue by gitone** [totorojs/totoro-server#56]
第一次使用totoro，各项配置完成之后， 基础的 mocha 或 jasmine能正确运行，但页面直接引入jquery就会超时，不知是何原因。 主要是想直接跑一个以前写的qunit的测试

**Comment by leoner** [comment]
目前测试框架只支持 mocha 和 jasmine. qunit 还不支持。后续会添加qunit 的适配的呀。

**Comment by fool2fish** [comment]
或者楼主贡献一个 qunit 的 adapter？

**Comment by lifesinger** [comment]
期待楼主贡献

On Tue, Dec 3, 2013 at 10:36 AM, Zhouxuan Yang notifications@github.comwrote:

> 或者楼主贡献一个 qunit 的 adapter？
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro-server/issues/56#issuecomment-29678805
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by gitone** [comment]
问题其实可以算作两个。
一个是totoro不支持qunit（事先不知道）； 
另一个是 在测试页面 单纯引入jq就会造成超时，引入其他脚本无此问题

**Comment by fool2fish** [comment]
第二个问题应该不会啊，有没有代码？我们看看

**Comment by gitone** [comment]
今天又重新跑了几次，未重现
