### ISSUE TITLE
日志监控分析从主流程中剥离

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro-server#58]
目前是在totoro-server 内部对日志进行分析处理，产生报表，而且这个还牵扯到数据库等信息配置，其实这些都不是 totoro-server 的主要功能，所以目前准备从 totoro-server 中把日志初步分析功能剥离出来，放到外部一个独立的服务中去做。

**Comment by popomore** [comment]
沉鱼不是要分享么，你们现在的日志大概包括哪些功能，貌似很多模块的定位都不一样。

**Comment by leoner** [comment]
这个应该和沉鱼说的不太一样，目前现在就是再 totoro-server 内部，去得到日志输出的信息，然后加工后存到数据库中，然后展现平台再从数据库里面获取相应的内容进行展现。 现在就想把分析和存数据的这个逻辑给摘出来。这样totoro-server 干净点呀。 然后原来 totoro-server 的日志输出方式应该就是沉鱼要分享的。

**Comment by popomore** [comment]
哦，日志模块的输出应该可以多端的，可以输出到终端，也可以生成文件或写数据库。Log4j 好像叫 Appender。

沉鱼分享的时候给说说现在有哪些常用的日志模块好了。

**Comment by leoner** [comment]
恩，是的，可以通过配置输出到各个地方。

**Comment by fool2fish** [comment]
恩，我们不算是有自己的日志模块，也是用的别人的，我想说的是，从哪些角度来帮助开发者选择一个合适自己的模块

康辉终于要迁走这块功能了，赞！
