### ISSUE TITLE
功能测试的讨论

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro-server#59]
目前和 alimama 团队初步讨论了功能测试的方案，主要思想就是采用数据驱动不同的页面展现，然后通过 loader(seajs, kissy) 扩展加载测试用例的方式。
目前再我们这边使用起来可能还有问题，不过等到我们 chair 出来后，这部分可以很容易的接入。下周去再杭州详细讨论下呀。

**Comment by lifesinger** [comment]
好

2013/12/13 hui notifications@github.com

> 目前和 alimama 团队初步讨论了功能测试的方案，主要思想就是采用数据驱动不同的页面展现，然后通过 loader(seajs, kissy)
> 扩展加载测试用例的方式。
> 目前再我们这边使用起来可能还有问题，不过等到我们 chair 出来后，这部分可以很容易的接入。下周去再杭州详细讨论下呀。
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro-server/issues/59
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香
