### ISSUE TITLE
改进代理的 url 映射关系

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro-server#62]
目前的规则：

```
{{client-host}}/path/to/runner  -> {{totoro-host}}/{{order-id}}/path/to/runner
```

使用这种映射关系，totoro 服务很容易知道一个代理请求所属的 order，静态资源使用绝对地址和相对地址都是没有问题的，但是如果是相对于根目录的地址，如 `/path/relative/to/root` 就不能正常解析。

目前北京广告团队和 kissy （还有karma）都有使用相对于根目录地址的需求。

初步设想解决方案：

```
{{client-host}}/path/to/runner  -> {{totoro-host}}/path/to/runner?__order_id={{order-id}}
```

除了 runner 本身外，其他静态资源的请求可以通过 http 头中的 `refer` 来判定所属 order。

注意：

此方案需要关闭缓存

另：为什么不使用浏览器代理？主要原因有三，一是不是所有的浏览器都好设置，二是对于临时挂载的浏览器来说，操作成本过高，三是客户端通常处在局域网内，{{client-host}} 可能重复（虽然概率不高）

**Comment by leoner** [comment]
赞!

**Comment by fool2fish** [comment]
关联提交： c2b530134e， 59147849bb ~ c36b36d47a

备忘：
1. 已将所有 runner 改成 /path/to/runner?__order_id={{orderId}} 的形式
2. 所有落入到 Proxy 处理的请求都关闭了缓存
3. 所有系统请求，除首页外，路径都加上了双下划线前缀。为避免新 url 隐射方案可能引发的冲突，以后的系统页面也应使用该类型前缀。
   `
   /__list           查看当前活跃 labors 的请求地址
   /__static/...   静态资源路径
   `
