### ISSUE TITLE
 totoro-server有更详细的教程吗？

### ISSUE THREAD

**Issue by RubyLouvre** [totorojs/totoro-server#65]
```
D:\>totoro-server
info C:\Users\qincheng.zhong.QUNARSERVERS\AppData\Roaming\npm\node_modules\totor
o-server\lib\index.js:69 | Start server <192.168.114.27:9999>
connect mongo server error!
```

我已经用npm成功安装它了，然后运行，报错。这东西要装mongo数据库吗？装完还要mongo连接库吗？你的教程不够详细……能详细解释一下吗。我们是去哪儿前端构架组，想用你的东西做多浏览器测试

**Comment by afc163** [comment]
https://github.com/totorojs/totoro-server/issues/54

**Comment by lifesinger** [comment]
司徒去去哪儿了呀

On Thu, Feb 27, 2014 at 12:10 PM, 偏右 notifications@github.com wrote:

> #54 https://github.com/totorojs/totoro-server/issues/54
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro-server/issues/65#issuecomment-36208551
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by fool2fish** [comment]
报这个错不影响正常使用的，我们周五就会发新版本v0.5.0，也就是明天，欢迎试用新版本呀，到时候文档什么的也会更完善的。要快速体验的话可以从源码安装，现在源码已经更新了。可能文档还会又少许修改。

**Comment by RubyLouvre** [comment]
意思说,芒果不是必须的?是,我就不安装了!如果否,那么安装后,还要干什么?

```
在服务器上开启totoro-server时,应配置server-host为服务器公网ip. 本机启动totoro命令时需注明totoro-server的server-host...
```

**Comment by RubyLouvre** [comment]
@lifesinger  嗯,离得近,搬家成本低

**Comment by fool2fish** [comment]
@RubyLouvre 之所以会报 db 错，是因为我们在 0.4 以前的版本写日志的时候同时写了一份到数据库，现在只写日志到日志文件里，所有的日志分析存储工作交由独立的 tla 模块来处理（这个模块只分析日志，不关心数据，或刚开始用 totoro 完全可以不要理会）

说了这么多，结论是：装了 totoro-server 就可以了，连上浏览器就能用了。

如果觉得使用还挺简单，想正式在团队中使用，那么就需要几台专用的测试机器，安装 browsers 模块，会帮你自动守护浏览器进程。

呃，totorojs.org 要把这些内容写上去啊

**Comment by thankwsx** [comment]
单独使用这个server可以构建一套测试矩阵吗？
估计答案是可以的。

那么再深入点想问下，server可以分发测试任务到不同的机器去吗？
有没有类似这样的server能做什么的介绍说明？
现在的文档还是不够详细啊。

**Comment by fool2fish** [comment]
关于 totoro 的 运行原理你可以看下这个keynote（看不了keynote的话就看pdf吧）：https://github.com/totorojs/totoro-server/tree/master/docs/totoro

现在测试就是分发到不同的机器上去执行的哦：）

**Comment by thankwsx** [comment]
@fool2fish  PDF page 23 有错别字。

**Comment by fool2fish** [comment]
@thankwsx 已更正，谢谢

**Comment by RubyLouvre** [comment]
能更详细一点吧，我是在window下安装，先npm install -g totoro，安装完成，再npm install -g totoro-server，安装完成，最后npm install browsers -g，安装完成。然后我想在D盘建立一个测试，如何搞，如何配置，怎么启动服务呢？你们的文档还是太简单了，不知所云

**Comment by RubyLouvre** [comment]
你们最好找一个不会JS的人，让他在一台安装好NPM的电脑上过一遍。教他怎么从totoro项目的example拷下来，然后怎么怎么配置，才能看到测试成功

**Comment by fool2fish** [comment]
就按照 totoro-server 文档的快速上手来啊，三步操作：1、`$ totoro-server` 2、浏览器访问 {{yourIP}}:9999 成为测试浏览器 3. 浏览器设置允许这个ip下的弹窗。

剩下就是 totoro 的快速上手了。

ps：好些其他团队都部署过了……那个时候文档还没现在全。你具体感觉哪里说的不清楚麻烦指出来，不然可能不知道怎么改进啊。

**Comment by RubyLouvre** [comment]
我要求totoro-server与totoro都装在同一台电脑上，但totoro 的快速上手了就运行不了

```
C:\Users\qincheng.zhong.QUNARSERVERS>totoro config --host server.totorojs.org

C:\Users\qincheng.zhong.QUNARSERVERS>totoro list
error C:\Users\qincheng.zhong.QUNARSERVERS\AppData\Roaming\npm\node_modules\toto
ro\lib\list.js:40 | Server is not available, please check your config or try aga
in later.
Call Stack:
    at ClientRequest.<anonymous> (C:\Users\qincheng.zhong.QUNARSERVERS\AppData\R
oaming\npm\node_modules\totoro\lib\list.js:40:16)
    at ClientRequest.EventEmitter.emit (events.js:104:17)
    at Socket.socketErrorListener (_http_client.js:239:9)
    at Socket.EventEmitter.emit (events.js:104:17)
    at net.js:433:14
    at process._tickCallback (node.js:664:11)

```

你有QQ吗，我们QQ聊

**Comment by RubyLouvre** [comment]
我的QQ是1669866773

**Comment by RubyLouvre** [comment]
我写一个教程

```
打开一个控制台
输入npm install -g totoro
输入npm install -g totoro-server
输入totoro-server
这时会看到
info 2014-03-03 14:03:58 index.js:66 | Start server <192.168.114.27:9999>
的字样,后面是IP地址与端口号
然后
打开你的firefox27 输入地址 http://192.168.114.27:9999/
打开你的IE10 输入地址 http://192.168.114.27:9999/
打开你的chrome33 输入地址 http://192.168.114.27:9999/

如果你有更多要测试的浏览器,也继续打开它们,注意你要设法让它们能弹窗

打开另一个控制台
输入 totoro config --host=192.168.114.27 --port=9999
输入 totoro list
这时就会看到

 Desktop:
   chrome 33.0.1750.117 / windows 7 [1]
   firefox 27.0 / windows 7 [1]
   ie 10.0 / windows 7 [1]
……
```

**Comment by RubyLouvre** [comment]
totoro config --host=192.168.114.27 --port=9999这一步没有反馈啊！

**Comment by RubyLouvre** [comment]
那个browsers 是怎么用的啊

**Comment by fool2fish** [comment]
`totoro config` 后面不跟参数会显示你刚刚的配置

看起来server已经配置成功了，谢谢，考虑更新到server的文档中去

**Comment by RubyLouvre** [comment]
那也要有反馈啊，死了也不知怎么回事

**Comment by fool2fish** [comment]
browsers 是个比较独立的模块，用于维护浏览器的稳定，不影响测试主流程。如果你刚安装 server，可以先跑一些测试看看，不一定要装 browsers。

要用的话也很简单：

`$ browsers --capture=192.168.114.27:9999 --browsers=ie,chrome` 找到你电脑上德ie和chrome，并访问你刚刚启动的服务地址

**Comment by fool2fish** [comment]
可以给 config 加一个配置反馈，我开个 issue 处理

**Comment by RubyLouvre** [comment]
firefox 工具 选项 内容 阻止弹出窗口  例外 --> 添加IP

**Comment by RubyLouvre** [comment]
chrome 设置 在展开的区域中找到 隐私设置   内容设置  弹出式窗口 管理例外情况  填入IP（192.168.114.27）

**Comment by RubyLouvre** [comment]
IE  Internet选项 隐私 启用窗口阻止程序,如果没有勾上就作罢,否则点设置,添加要允许的网站地址(http://192.168.114.27:9999/)

**Comment by Delan1026** [comment]
我电脑配置是Windows 7 64bit, 装了 .NET Framework 4.5, 执行npm install -g totoro 提示无法找打VCBuild.exe, 然后下载了Mircrosoft Windows SDK for windows 2008, 把C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\vcpackages 路径配置到path环境变量里面，这时没有提示找不到vcbuild.exe了，提示说build.sln不是一个有效的project文件，纠结啊。
首先非常感谢你们把这么好的东西分享出来，既然你们花了那么大的力气研究这个东西，为什么就不舍得花点时间写个详细点的文档呢？这样就有更多的人使用这个工具，也可以发现里面的一些问题。也可能我足够笨，看不懂你们的安装步骤。
