### ISSUE TITLE
接入测试覆盖率

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro-server#7]
- 考察覆盖率工具
  - [jscoverage](https://github.com/fishbar/jscoverage)
  - [blanket](http://blanketjs.org/)
  - [istanbul](https://github.com/gotwarlost/istanbul)
- 覆盖率工具对代码或者目录结构的要求
  - 可能只支持本地代码（这样就需要去掉 --runner 对 url 的支持）
  - 固定项目目录的规范，不支持那么灵活的 runner 查找方式？

**Comment by lepture** [comment]
@fool2fish 你应该参考的不是 jscoverage 这个，而是另外一个。

**Comment by lepture** [comment]
@fool2fish https://github.com/alex-seville/blanket

**Comment by lifesinger** [comment]
对，去看看 blanket

On Sat, Jun 1, 2013 at 9:31 AM, Hsiaoming Yang notifications@github.comwrote:

> @fool2fish https://github.com/fool2fish
> https://github.com/alex-seville/blanket
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro-server/issues/7#issuecomment-18781468
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by lifesinger** [comment]
blanket 小高搞个微分享吧

On Sat, Jun 1, 2013 at 4:51 PM, Frank Wang lifesinger@gmail.com wrote:

> 对，去看看 blanket
> 
> On Sat, Jun 1, 2013 at 9:31 AM, Hsiaoming Yang notifications@github.comwrote:
> 
> > @fool2fish https://github.com/fool2fish
> > https://github.com/alex-seville/blanket
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro-server/issues/7#issuecomment-18781468
> > .
> 
> ## 
> 
> 王保平 / 玉伯（射雕）
> 送人玫瑰手有余香

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by fool2fish** [comment]
jscoverage 是个好东西，简单又好用，还不依赖于任何特定的加载方式和测试框架，就用它了

**Comment by fool2fish** [comment]
先粗糙地实现着，稍后需要重构的地方：
1. 对需要进行 coverage 处理的判断  proxy.js (line:118)
2. 格式化 _$jscoverage  static/labor.html (line:144)
3. 添加了 coverage 功能后，labor.html 中为什么在 ie 下必须给 iframe 添加 id？ static/labor.html (line:88)

**Comment by fishbar** [comment]
jscoverage 更新了， 欢迎继续使用
