### ISSUE TITLE
让totoro自动打开某一个浏览器

### ISSUE THREAD

**Issue by RubyLouvre** [totorojs/totoro-server#70]
虽然运行了totoro-server后会告诉你的IP地址与端口号，但在控制台手动复制它们，
再逐个打开浏览器的体验实在太差了
建议看我这篇博文<a href="http://www.cnblogs.com/rubylouvre/archive/2013/01/10/2854040.html">《node.js打开浏览器》</a>

让它打开默认浏览器，然后在页面上提示用户再打开其他浏览器

另外  totoro config --host=192.168.114.27 --port=9999 太复杂了

建议精简为 totoro config --location=http://192.168.114.27:9999/ 

因为后面的地址能直接从浏览器复制下来贴上

**Comment by fool2fish** [comment]
totoro 是数个有独立功能的小模块组合而成的，browsers 这个模块就是浏览器守护程序，可以打开浏览器访问url之类的。ps：browsers 完成的，不仅仅是打开浏览器

一般只用配置 --host 不用配置 --port 啊，你只要不改默认配置
