### ISSUE TITLE
如果以chunk响应，proxy还读content-length导致错误buffer长度错误

### ISSUE THREAD

**Issue by sodawy** [totorojs/totoro-server#73]
lib/proxy中176行

``` javascript
var buffer = new Buffer(parseInt(res.headers['content-length'], 10))
```

为了测试线上代码，用node做了一个proxy，用来请求目标资源，并注入测试脚本，然后返给totoro-server，但当html很大时，会被自动截断，不知道为啥会被截断，反正不能用content-length了。于是响应变成了chunk的。

跟到上面引用的代码，导致buffer长度错误，响应内容就都是空了。

多谢

**Comment by fool2fish** [comment]
能在你的 github 中给出最少能说明问题的代码么？

**Comment by sodawy** [comment]
感谢回复。

#### 我不知道我的思路是不是正确，以下是简要描述：

1、我想测试线上代码
2、我自己攒了个node server做proxy，比如这样调用：

``` shell
totoro -R http://10.211.55.2:9998/proxy?target=hotel.qunar.com -a mocha
```

3、在proxy中，把线上代码注入mocha和case，返给totoro-server

攒的proxy代码地址：https://gist.github.com/soda-wy/11307902

#### 遇到的问题

当我重新拼接完html返给totoro-server时，遇到html被截断(我在浏览器上看到的结果)，所以我去掉了content-length，希望以chunk方式返回给totoro-server，而totoro-server中读响应是要看content-length的:

``` javascript
var buffer = new Buffer(parseInt(res.headers['content-length'], 10))
```

这导致我拼接后的响应到totoro-server后，buffer length变成了0. 于是totoro抛出了

``` shell
Adapter error. Can not decide where to insert adapter
```

请指正~~多谢

**Comment by sodawy** [comment]
### 我的问题解决了。可以无视我上面的comment了

我自己的代理在响应前，将str转成了buffer。https://gist.github.com/soda-wy/11307902/revisions

``` javascript
//以buffer而非string传输，提高效率、避免因过长而截断
html = new Buffer(html);
response.setHeader('Content-Length', html.length);
```

#### 但totoro-server /lib/proxy.js中，在response无content-length时，问题依然存在。

``` javascript
var buffer = new Buffer(parseInt(res.headers['content-length'], 10))
```

**Comment by fool2fish** [comment]
没有 content-length 的 http 头本身就是不规范的呀，如果没有这个，totoro-server 插入 adapter 之后就不知道 length 是多少了

**Comment by sodawy** [comment]
http1.1的话，不给content-length就按chunk，不算不规范吧？

**Comment by fool2fish** [comment]
> Applications SHOULD use this field to indicate the transfer-length of the message-body, unless this is prohibited by the rules in section 4.4.

查了下规范，还真是 SHOULD，不是 MUST. 先记一下，后续 fix 掉。

**Comment by leoner** [comment]
重新修改了proxy 对 buffer 的处理方式, 这个问题应该已修复.

**Comment by fool2fish** [comment]
已修复，见提交： e0468fc367
