### ISSUE TITLE
使用专门的 ajax 库替换 jquery 报告测试结果

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro-server#78]
如题，一来减少文件大小，而来避免用户使用特定版本功能的冲突

**Comment by jserme** [comment]
晕。。。原来已经记了这个问题

http://microjs.com/#ajax 

可以在这里挑一个兼容性测试完整的专门用来ajax的库

**Comment by leoner** [comment]
https://github.com/ForbesLindesay/ajax 暂确定用这个.
