### ISSUE TITLE
系统日志

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro-server#8]
基本需求：
- 当测试无法正常完成测试是，需要知道具体原因，比如指定了没有的浏览器，配置不当等等，以便进行更好的引导
- 如果系统崩溃，需要知道崩溃时的状态，比如总是某一个测试引起系统崩溃，或者走到那个阶段会系统崩溃

关联问题：
- 日志内容的书写规范
- 想采集的数据以及如何进行日志分析

```
{
    totalTests : 20,
    succ : 18,
    failure : 2,
    averageTC : 23,
    averageCov : 83,
    averageDuration : 33,
    maxTC : [repoName, tcAmount],
    minTC : [repoName, tcAmount]
    maxCov : [repoName, cov],
    minCov : [repoName, cov]
    children : {
        "20130713" : {
            totalTests : 20,
            succ : 18,
            failure : 2,
            averageTC : 23,
            averageCov : 83,
            averageDuration : 33,
            maxTC : [repoName, tcAmount],
            minTC : [repoName, tcAmount]
            maxCov : [repoName, cov],
            minCov : [repoName, cov]
            children: {
                "totoro.git" : {
                    ...
                },
                "null" : {
                    ...
                }
            }
        }
    }
}
```

**Comment by fool2fish** [comment]
希望拿到以下数据：
- 每天跑了多少次测试
- 每个测试耗时多少
- 关键路径耗时：代理请求，adapte和插入覆盖率代码操作
- 测试结果：成功多少，覆盖率如何，失败的原因是什么

**Comment by leoner** [comment]
- 测试模块名称: 耗时, 测试次数, (是否添加测试人? 从本地读取)
- 测试失败模块记录: 模块名, 错误信息

**Comment by leoner** [comment]
- 提供接口, 当客户端发生错误时, 进行调用. 统计客户端错误信息.

**Comment by fool2fish** [comment]
## 一些参考

### 关键日志点
- 性能
- 错误
- 端到端业务监控
- 定时状态报告 
- 服务边界(内部/外部 )
- 报文签名

### 消息级别
- TRACE: 用于开发场景的应用调试，类似调试器的单步跟踪模式
- DEBUG: 用于开发场景应用调试，输出详细的应用状态
- INFO: 用于生产环境运行状态观察，输出应用生命周期的中正常重要事件
- WARN: 用于生产环境故障诊断，输出应用中的可预期的异常事件，但正在处理的业务请求仍可继续，信息供系统调优使用或者服务客户使用，不需要处理
- ERROR: 用于生产环境故障诊断，输出应用中的未预期的异常事件，当前的业务请求已无法继续处理，但其它业务请求仍可继续，需要处理
- FATAL: 用于生产环境故障报告，输出应用中的未预期的异常事件，应用整体不可用，必须立即处理

### 故障诊断
- 大面积故障的诊断方案
- 单个用户故障的诊断方案
- 经常分享并改进方案
- 将方案集中存放在共享空间，供大家参考、review与使用？

**Comment by fool2fish** [comment]
### 待确定
- 日志格式
- 关键路径日志
- 性能监控
- 日志文件，按多少时间输出，是否按类别输出

**Comment by fool2fish** [comment]
## 方案
1. 日志文件按天区分，所有类型的日志统一输出到一个文件中，可使用 grep 进行分类查看（主要考虑到要对关键流程进行追踪，如果要按日志类型进行文件区分的话，异常流难以分析）
2. 日志格式：type date file:line msg，格式化列对齐，对于 msg 中的关键信息，使用 key:value 的方式表示属性，如 new order:orderId
3. 自行记录关键步骤耗时

**Comment by hotoo** [comment]
一般日志如下存储：
- 不同的业务日志存储在不同的日志文件中，如 error.log, access.log 等。
- 日志一般使用 cronlog 来按日拆分
- 建议使用一致的分隔符拆分各个字段，而不是 key:value

**Comment by leoner** [comment]
```
 Labor<krKrkJh3fnUffIOWcFl-> remove order<QaWIFkbZ3ohgL3MKcFmB>
debug 2013-08-02 04:04:13 C:\Users\Administrator\AppData\Roaming\npm\node_modules\totoro-server\lib\order.js:168 | Order<QaWIFkbZ3ohgL3MKcFmB> destroy.
```

```
order.js:147 | All labors finished order<7zIPfu82OhwOlmv-cFmD>, total time<49204>
debug 2013-08-02 04:05:21 C:\Users\Administrator\AppData\Roaming\npm\node_modules\totoro-server\lib\labor.js:89  | Labor<G-qrOpGgV1J1a0jWcFmE> remove order<7zIPfu82OhwOlmv-cFmD>
debug 2013-08-02 04:05:22 C:\Users\Administrator\AppData\Roaming\npm\node_modules\totoro-server\lib\order.js:168 | Order<7zIPfu82OhwOlmv-cFmD> destroy.
```

就是 Order 成功后, 会有一个 **All labors finished order** 的标志. 而某个Order 中的 Labor 失败后, 会没有这个信息. 那么也就是获取不到 totalTime .

**Comment by leoner** [comment]
Order 非正常结束的时候, 会没有 totalTime
