### ISSUE TITLE
在windows7运行totoro-server出错

### ISSUE THREAD

**Issue by semious** [totorojs/totoro-server#85]
C:\Users\semious>totoro-server

C:\Users\semious\AppData\Roaming\npm\node_modules\totoro-server\node_modules\col
orful\lib\ansi.js:39
  term = term.toLowerCase();
              ^
TypeError: Cannot call method 'toLowerCase' of undefined
    at is256ColorSupported (C:\Users\semious\AppData\Roaming\npm\node_modules\to
toro-server\node_modules\colorful\lib\ansi.js:39:15)
    at Object.exports.color.grey.exports.color.gray.exports.grey.exports.gray [a
s info](C:UserssemiousAppDataRoamingnpmnode_modulestotoro-servernode_mo
dulescolorfullibansi.js:111:7)
    at Object.module.exports.tracer.console.transport (C:\Users\semious\AppData\
Roaming\npm\node_modules\totoro-server\lib\logger.js:34:31)
    at module.exports._log (C:\Users\semious\AppData\Roaming\npm\node_modules\to
toro-server\node_modules\tracer\lib\console.js:71:18)
    at Object.module.exports [as info](C:UserssemiousAppDataRoamingnpmnod
e_modulestotoro-servernode_modulestracerlibconsole.js:115:13)
    at Server.<anonymous> (C:\Users\semious\AppData\Roaming\npm\node_modules\tot
oro-server\lib\index.js:71:12)
    at Server.g (events.js:180:16)
    at Server.EventEmitter.emit (events.js:117:20)
    at net.js:1052:10
    at process._tickCallback (node.js:415:13)

**Comment by hbrls** [comment]
+1，另外为什么不用成熟一些的库呢，比如 cli-color

**Comment by fool2fish** [comment]
呃，看来不是个例，我们会尽快修复

**Comment by bingdiemylove** [comment]
+1，今天更新totoro-server之后出现这个问题！

**Comment by fool2fish** [comment]
更新下 node 和 npm 的版本。在 win7 下面亲测了下，比较老得版本确实会报错，错误跟楼上提到的还不一样，更新版本后错误解决。

**Comment by AlixKang** [comment]
Hi, 更新到最新的node(直接下载的.exe), 重新从源码安装的npm,  还是有这个错误(TypeError: Cannot call method 'toLowerCase' of undefined).  可否告知下你的npm 和node版本，谢谢;] 

---

```
C: node -v
v0.10.29
C: npm -v
1.5.0-alpha-1
```

**Comment by fool2fish** [comment]
我是在 http://nodejs.org/download/ 这个页面下载 windows 64位 msi 文件安装的，node 和 npm 都在里面了

**Comment by semious** [comment]
@fool2fish @AlixKang @bingdiemylove @shuaishuai 
原因已经找到，老版的color这行代码不严谨，在某些window的环境下 拿不到TERM的，
  var term = process.env.TERM;

  term = term.toLowerCase();

因此在新版的color里，改成了如下代码
 var term = process.env.TERM;
  if (!term) return false;

  term = term.toLowerCase();

在totoro-server里引用的是"colorful": "2.0.2", 建议改成"colorful": "2.1.0",

本地修改ansi.js文件完毕后，顺利跑起totoro-server

**Comment by semious** [comment]
![image](https://cloud.githubusercontent.com/assets/846252/3690828/47993126-134c-11e4-873a-bedc2ac23ae3.png)

截个图 庆贺一下，呵呵，看来还是自给自足，丰衣足食哈 ~~

**Comment by AlixKang** [comment]
@semious 
谢谢分享;]

**Comment by fool2fish** [comment]
@semious  多谢帮忙排查原因：）
