### ISSUE TITLE
今天升级最新版后报错

### ISSUE THREAD

**Issue by RubyLouvre** [totorojs/totoro-server#87]
输入npm install -g totoro

输入npm install -g totoro-server

输入totoro-server
然后就报错了

![image](https://cloud.githubusercontent.com/assets/190846/3868910/724e287a-206e-11e4-8c93-ef63935c318e.png)

**Comment by afc163** [comment]
https://github.com/totorojs/totoro-server/issues/85

**Comment by RubyLouvre** [comment]
好了，觉得totoro-server依赖的东西太多，质量没什么保证，像FIS那样，能自己写的基本自己，全部由自己hold住比较安全

**Comment by afc163** [comment]
能依赖就依赖，自己写才累
